apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-go-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-go-project
  template:
    metadata:
      labels:
        app: kubernetes-go-project
    spec:
      containers:
      - name: kubernetes-go-project
        image: <your-docker-username>/kubernetes-go-project:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-go-project
spec:
  selector:
    app: kubernetes-go-project
  ports:
    - name: http
      port: 80
      targetPort: 8080
